# Generated by Django 3.2 on 2022-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Hospital'), (2, 'User'), (3, 'Admin'), (4, 'Trainer')], default=3, null=True),
        ),
    ]
