# Generated by Django 3.2 on 2022-09-01 07:41

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=about.models.trainer_profile),
        ),
    ]
