# Generated by Django 3.2 on 2022-09-01 08:49

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(blank=True, default='/profile.png', null=True, upload_to=about.models.trainer_profile),
        ),
    ]
